// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: fcfsapi/service.proto

package fcfsapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_fcfsapi_service_proto protoreflect.FileDescriptor

const file_fcfsapi_service_proto_rawDesc = "" +
	"\n" +
	"\x15fcfsapi/service.proto\x12\afcfsapi\x1a\x16fcfsapi/location.proto\x1a\x16fcfsapi/forecast.proto\x1a\x16fcfsapi/quartzui.proto2\x9e\b\n" +
	"\tQuartzAPI\x12m\n" +
	"\x16GetPredictedTimeseries\x12&.fcfsapi.GetPredictedTimeseriesRequest\x1a'.fcfsapi.GetPredictedTimeseriesResponse\"\x000\x01\x12d\n" +
	"\x13GetActualTimeseries\x12#.fcfsapi.GetActualTimeseriesRequest\x1a$.fcfsapi.GetActualTimeseriesResponse\"\x000\x01\x12q\n" +
	"\x18GetPredictedCrossSection\x12(.fcfsapi.GetPredictedCrossSectionRequest\x1a).fcfsapi.GetPredictedCrossSectionResponse\"\x00\x12h\n" +
	"\x15GetActualCrossSection\x12%.fcfsapi.GetActualCrossSectionRequest\x1a&.fcfsapi.GetActualCrossSectionResponse\"\x00\x12\\\n" +
	"\x11GetLatestForecast\x12!.fcfsapi.GetLatestForecastRequest\x1a\".fcfsapi.GetLatestForecastResponse\"\x00\x12h\n" +
	"\x15GetLocationsAsGeoJSON\x12%.fcfsapi.GetLocationsAsGeoJSONRequest\x1a&.fcfsapi.GetLocationsAsGeoJSONResponse\"\x00\x12P\n" +
	"\x0fCreateSolarSite\x12\x1a.fcfsapi.CreateSiteRequest\x1a\x1f.fcfsapi.CreateLocationResponse\"\x00\x12N\n" +
	"\x0eCreateSolarGsp\x12\x19.fcfsapi.CreateGspRequest\x1a\x1f.fcfsapi.CreateLocationResponse\"\x00\x12O\n" +
	"\x10GetSolarLocation\x12\x1b.fcfsapi.GetLocationRequest\x1a\x1c.fcfsapi.GetLocationResponse\"\x00\x12J\n" +
	"\vCreateModel\x12\x1b.fcfsapi.CreateModelRequest\x1a\x1c.fcfsapi.CreateModelResponse\"\x00\x12X\n" +
	"\x13CreateSolarForecast\x12\x1e.fcfsapi.CreateForecastRequest\x1a\x1f.fcfsapi.CreateForecastResponse\"\x00B@Z>github.com/devsjc/fcfs/api/src/internal/models/fcfsapi;fcfsapib\x06proto3"

var file_fcfsapi_service_proto_goTypes = []any{
	(*GetPredictedTimeseriesRequest)(nil),    // 0: fcfsapi.GetPredictedTimeseriesRequest
	(*GetActualTimeseriesRequest)(nil),       // 1: fcfsapi.GetActualTimeseriesRequest
	(*GetPredictedCrossSectionRequest)(nil),  // 2: fcfsapi.GetPredictedCrossSectionRequest
	(*GetActualCrossSectionRequest)(nil),     // 3: fcfsapi.GetActualCrossSectionRequest
	(*GetLatestForecastRequest)(nil),         // 4: fcfsapi.GetLatestForecastRequest
	(*GetLocationsAsGeoJSONRequest)(nil),     // 5: fcfsapi.GetLocationsAsGeoJSONRequest
	(*CreateSiteRequest)(nil),                // 6: fcfsapi.CreateSiteRequest
	(*CreateGspRequest)(nil),                 // 7: fcfsapi.CreateGspRequest
	(*GetLocationRequest)(nil),               // 8: fcfsapi.GetLocationRequest
	(*CreateModelRequest)(nil),               // 9: fcfsapi.CreateModelRequest
	(*CreateForecastRequest)(nil),            // 10: fcfsapi.CreateForecastRequest
	(*GetPredictedTimeseriesResponse)(nil),   // 11: fcfsapi.GetPredictedTimeseriesResponse
	(*GetActualTimeseriesResponse)(nil),      // 12: fcfsapi.GetActualTimeseriesResponse
	(*GetPredictedCrossSectionResponse)(nil), // 13: fcfsapi.GetPredictedCrossSectionResponse
	(*GetActualCrossSectionResponse)(nil),    // 14: fcfsapi.GetActualCrossSectionResponse
	(*GetLatestForecastResponse)(nil),        // 15: fcfsapi.GetLatestForecastResponse
	(*GetLocationsAsGeoJSONResponse)(nil),    // 16: fcfsapi.GetLocationsAsGeoJSONResponse
	(*CreateLocationResponse)(nil),           // 17: fcfsapi.CreateLocationResponse
	(*GetLocationResponse)(nil),              // 18: fcfsapi.GetLocationResponse
	(*CreateModelResponse)(nil),              // 19: fcfsapi.CreateModelResponse
	(*CreateForecastResponse)(nil),           // 20: fcfsapi.CreateForecastResponse
}
var file_fcfsapi_service_proto_depIdxs = []int32{
	0,  // 0: fcfsapi.QuartzAPI.GetPredictedTimeseries:input_type -> fcfsapi.GetPredictedTimeseriesRequest
	1,  // 1: fcfsapi.QuartzAPI.GetActualTimeseries:input_type -> fcfsapi.GetActualTimeseriesRequest
	2,  // 2: fcfsapi.QuartzAPI.GetPredictedCrossSection:input_type -> fcfsapi.GetPredictedCrossSectionRequest
	3,  // 3: fcfsapi.QuartzAPI.GetActualCrossSection:input_type -> fcfsapi.GetActualCrossSectionRequest
	4,  // 4: fcfsapi.QuartzAPI.GetLatestForecast:input_type -> fcfsapi.GetLatestForecastRequest
	5,  // 5: fcfsapi.QuartzAPI.GetLocationsAsGeoJSON:input_type -> fcfsapi.GetLocationsAsGeoJSONRequest
	6,  // 6: fcfsapi.QuartzAPI.CreateSolarSite:input_type -> fcfsapi.CreateSiteRequest
	7,  // 7: fcfsapi.QuartzAPI.CreateSolarGsp:input_type -> fcfsapi.CreateGspRequest
	8,  // 8: fcfsapi.QuartzAPI.GetSolarLocation:input_type -> fcfsapi.GetLocationRequest
	9,  // 9: fcfsapi.QuartzAPI.CreateModel:input_type -> fcfsapi.CreateModelRequest
	10, // 10: fcfsapi.QuartzAPI.CreateSolarForecast:input_type -> fcfsapi.CreateForecastRequest
	11, // 11: fcfsapi.QuartzAPI.GetPredictedTimeseries:output_type -> fcfsapi.GetPredictedTimeseriesResponse
	12, // 12: fcfsapi.QuartzAPI.GetActualTimeseries:output_type -> fcfsapi.GetActualTimeseriesResponse
	13, // 13: fcfsapi.QuartzAPI.GetPredictedCrossSection:output_type -> fcfsapi.GetPredictedCrossSectionResponse
	14, // 14: fcfsapi.QuartzAPI.GetActualCrossSection:output_type -> fcfsapi.GetActualCrossSectionResponse
	15, // 15: fcfsapi.QuartzAPI.GetLatestForecast:output_type -> fcfsapi.GetLatestForecastResponse
	16, // 16: fcfsapi.QuartzAPI.GetLocationsAsGeoJSON:output_type -> fcfsapi.GetLocationsAsGeoJSONResponse
	17, // 17: fcfsapi.QuartzAPI.CreateSolarSite:output_type -> fcfsapi.CreateLocationResponse
	17, // 18: fcfsapi.QuartzAPI.CreateSolarGsp:output_type -> fcfsapi.CreateLocationResponse
	18, // 19: fcfsapi.QuartzAPI.GetSolarLocation:output_type -> fcfsapi.GetLocationResponse
	19, // 20: fcfsapi.QuartzAPI.CreateModel:output_type -> fcfsapi.CreateModelResponse
	20, // 21: fcfsapi.QuartzAPI.CreateSolarForecast:output_type -> fcfsapi.CreateForecastResponse
	11, // [11:22] is the sub-list for method output_type
	0,  // [0:11] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_fcfsapi_service_proto_init() }
func file_fcfsapi_service_proto_init() {
	if File_fcfsapi_service_proto != nil {
		return
	}
	file_fcfsapi_location_proto_init()
	file_fcfsapi_forecast_proto_init()
	file_fcfsapi_quartzui_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fcfsapi_service_proto_rawDesc), len(file_fcfsapi_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fcfsapi_service_proto_goTypes,
		DependencyIndexes: file_fcfsapi_service_proto_depIdxs,
	}.Build()
	File_fcfsapi_service_proto = out.File
	file_fcfsapi_service_proto_goTypes = nil
	file_fcfsapi_service_proto_depIdxs = nil
}
