// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: api.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	QuartzAPI_GetPredictedTimeseries_FullMethodName   = "/api.QuartzAPI/GetPredictedTimeseries"
	QuartzAPI_GetActualTimeseries_FullMethodName      = "/api.QuartzAPI/GetActualTimeseries"
	QuartzAPI_GetActualCrossSection_FullMethodName    = "/api.QuartzAPI/GetActualCrossSection"
	QuartzAPI_GetPredictedCrossSection_FullMethodName = "/api.QuartzAPI/GetPredictedCrossSection"
	QuartzAPI_CreateSolarSite_FullMethodName          = "/api.QuartzAPI/CreateSolarSite"
	QuartzAPI_CreateWindSite_FullMethodName           = "/api.QuartzAPI/CreateWindSite"
	QuartzAPI_CreateSolarGsp_FullMethodName           = "/api.QuartzAPI/CreateSolarGsp"
	QuartzAPI_CreateWindGsp_FullMethodName            = "/api.QuartzAPI/CreateWindGsp"
)

// QuartzAPIClient is the client API for QuartzAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QuartzAPIClient interface {
	// GetPredictedTimeseriesRequest is a request for a set of predicted yields for one or more locations.
	// The response is a stream of GetPredictedTimeseriesResponse messages.
	// each containing the predicted yields for a single location.
	GetPredictedTimeseries(ctx context.Context, in *GetPredictedTimeseriesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetPredictedTimeseriesResponse], error)
	// GetActualTimeseriesRequest is a request for a set of actual yields for one or more locations.
	// The response is a stream of GetActualTimeseriesResponse messages.
	// each containing the actual yields for a single location.
	GetActualTimeseries(ctx context.Context, in *GetActualTimeseriesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetActualTimeseriesResponse], error)
	// GetActualCrossSectionRequest is a request for a specific actual yield for one or more locations
	// at a single timestamp. The response is a GetActualCrossSectionResponse message containing the
	// actual yields for each location.
	GetActualCrossSection(ctx context.Context, in *GetActualCrossSectionRequest, opts ...grpc.CallOption) (*GetActualCrossSectionResponse, error)
	// GetPredictedCrossSectionRequest is a request for a specific predicted yield for one or more locations
	// at a single timestamp. The response is a GetPredictedCrossSectionResponse message containing the
	// predicted yields for each location.
	GetPredictedCrossSection(ctx context.Context, in *GetPredictedCrossSectionRequest, opts ...grpc.CallOption) (*GetPredictedCrossSectionResponse, error)
	CreateSolarSite(ctx context.Context, in *CreateSiteRequest, opts ...grpc.CallOption) (*CreateLocationResponse, error)
	CreateWindSite(ctx context.Context, in *CreateSiteRequest, opts ...grpc.CallOption) (*CreateLocationResponse, error)
	CreateSolarGsp(ctx context.Context, in *CreateGspRequest, opts ...grpc.CallOption) (*CreateLocationResponse, error)
	CreateWindGsp(ctx context.Context, in *CreateGspRequest, opts ...grpc.CallOption) (*CreateLocationResponse, error)
}

type quartzAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewQuartzAPIClient(cc grpc.ClientConnInterface) QuartzAPIClient {
	return &quartzAPIClient{cc}
}

func (c *quartzAPIClient) GetPredictedTimeseries(ctx context.Context, in *GetPredictedTimeseriesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetPredictedTimeseriesResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &QuartzAPI_ServiceDesc.Streams[0], QuartzAPI_GetPredictedTimeseries_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetPredictedTimeseriesRequest, GetPredictedTimeseriesResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type QuartzAPI_GetPredictedTimeseriesClient = grpc.ServerStreamingClient[GetPredictedTimeseriesResponse]

func (c *quartzAPIClient) GetActualTimeseries(ctx context.Context, in *GetActualTimeseriesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetActualTimeseriesResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &QuartzAPI_ServiceDesc.Streams[1], QuartzAPI_GetActualTimeseries_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetActualTimeseriesRequest, GetActualTimeseriesResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type QuartzAPI_GetActualTimeseriesClient = grpc.ServerStreamingClient[GetActualTimeseriesResponse]

func (c *quartzAPIClient) GetActualCrossSection(ctx context.Context, in *GetActualCrossSectionRequest, opts ...grpc.CallOption) (*GetActualCrossSectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetActualCrossSectionResponse)
	err := c.cc.Invoke(ctx, QuartzAPI_GetActualCrossSection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quartzAPIClient) GetPredictedCrossSection(ctx context.Context, in *GetPredictedCrossSectionRequest, opts ...grpc.CallOption) (*GetPredictedCrossSectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPredictedCrossSectionResponse)
	err := c.cc.Invoke(ctx, QuartzAPI_GetPredictedCrossSection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quartzAPIClient) CreateSolarSite(ctx context.Context, in *CreateSiteRequest, opts ...grpc.CallOption) (*CreateLocationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateLocationResponse)
	err := c.cc.Invoke(ctx, QuartzAPI_CreateSolarSite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quartzAPIClient) CreateWindSite(ctx context.Context, in *CreateSiteRequest, opts ...grpc.CallOption) (*CreateLocationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateLocationResponse)
	err := c.cc.Invoke(ctx, QuartzAPI_CreateWindSite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quartzAPIClient) CreateSolarGsp(ctx context.Context, in *CreateGspRequest, opts ...grpc.CallOption) (*CreateLocationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateLocationResponse)
	err := c.cc.Invoke(ctx, QuartzAPI_CreateSolarGsp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quartzAPIClient) CreateWindGsp(ctx context.Context, in *CreateGspRequest, opts ...grpc.CallOption) (*CreateLocationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateLocationResponse)
	err := c.cc.Invoke(ctx, QuartzAPI_CreateWindGsp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuartzAPIServer is the server API for QuartzAPI service.
// All implementations should embed UnimplementedQuartzAPIServer
// for forward compatibility.
type QuartzAPIServer interface {
	// GetPredictedTimeseriesRequest is a request for a set of predicted yields for one or more locations.
	// The response is a stream of GetPredictedTimeseriesResponse messages.
	// each containing the predicted yields for a single location.
	GetPredictedTimeseries(*GetPredictedTimeseriesRequest, grpc.ServerStreamingServer[GetPredictedTimeseriesResponse]) error
	// GetActualTimeseriesRequest is a request for a set of actual yields for one or more locations.
	// The response is a stream of GetActualTimeseriesResponse messages.
	// each containing the actual yields for a single location.
	GetActualTimeseries(*GetActualTimeseriesRequest, grpc.ServerStreamingServer[GetActualTimeseriesResponse]) error
	// GetActualCrossSectionRequest is a request for a specific actual yield for one or more locations
	// at a single timestamp. The response is a GetActualCrossSectionResponse message containing the
	// actual yields for each location.
	GetActualCrossSection(context.Context, *GetActualCrossSectionRequest) (*GetActualCrossSectionResponse, error)
	// GetPredictedCrossSectionRequest is a request for a specific predicted yield for one or more locations
	// at a single timestamp. The response is a GetPredictedCrossSectionResponse message containing the
	// predicted yields for each location.
	GetPredictedCrossSection(context.Context, *GetPredictedCrossSectionRequest) (*GetPredictedCrossSectionResponse, error)
	CreateSolarSite(context.Context, *CreateSiteRequest) (*CreateLocationResponse, error)
	CreateWindSite(context.Context, *CreateSiteRequest) (*CreateLocationResponse, error)
	CreateSolarGsp(context.Context, *CreateGspRequest) (*CreateLocationResponse, error)
	CreateWindGsp(context.Context, *CreateGspRequest) (*CreateLocationResponse, error)
}

// UnimplementedQuartzAPIServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQuartzAPIServer struct{}

func (UnimplementedQuartzAPIServer) GetPredictedTimeseries(*GetPredictedTimeseriesRequest, grpc.ServerStreamingServer[GetPredictedTimeseriesResponse]) error {
	return status.Errorf(codes.Unimplemented, "method GetPredictedTimeseries not implemented")
}
func (UnimplementedQuartzAPIServer) GetActualTimeseries(*GetActualTimeseriesRequest, grpc.ServerStreamingServer[GetActualTimeseriesResponse]) error {
	return status.Errorf(codes.Unimplemented, "method GetActualTimeseries not implemented")
}
func (UnimplementedQuartzAPIServer) GetActualCrossSection(context.Context, *GetActualCrossSectionRequest) (*GetActualCrossSectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActualCrossSection not implemented")
}
func (UnimplementedQuartzAPIServer) GetPredictedCrossSection(context.Context, *GetPredictedCrossSectionRequest) (*GetPredictedCrossSectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPredictedCrossSection not implemented")
}
func (UnimplementedQuartzAPIServer) CreateSolarSite(context.Context, *CreateSiteRequest) (*CreateLocationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSolarSite not implemented")
}
func (UnimplementedQuartzAPIServer) CreateWindSite(context.Context, *CreateSiteRequest) (*CreateLocationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWindSite not implemented")
}
func (UnimplementedQuartzAPIServer) CreateSolarGsp(context.Context, *CreateGspRequest) (*CreateLocationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSolarGsp not implemented")
}
func (UnimplementedQuartzAPIServer) CreateWindGsp(context.Context, *CreateGspRequest) (*CreateLocationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWindGsp not implemented")
}
func (UnimplementedQuartzAPIServer) testEmbeddedByValue() {}

// UnsafeQuartzAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QuartzAPIServer will
// result in compilation errors.
type UnsafeQuartzAPIServer interface {
	mustEmbedUnimplementedQuartzAPIServer()
}

func RegisterQuartzAPIServer(s grpc.ServiceRegistrar, srv QuartzAPIServer) {
	// If the following call pancis, it indicates UnimplementedQuartzAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QuartzAPI_ServiceDesc, srv)
}

func _QuartzAPI_GetPredictedTimeseries_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetPredictedTimeseriesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(QuartzAPIServer).GetPredictedTimeseries(m, &grpc.GenericServerStream[GetPredictedTimeseriesRequest, GetPredictedTimeseriesResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type QuartzAPI_GetPredictedTimeseriesServer = grpc.ServerStreamingServer[GetPredictedTimeseriesResponse]

func _QuartzAPI_GetActualTimeseries_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetActualTimeseriesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(QuartzAPIServer).GetActualTimeseries(m, &grpc.GenericServerStream[GetActualTimeseriesRequest, GetActualTimeseriesResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type QuartzAPI_GetActualTimeseriesServer = grpc.ServerStreamingServer[GetActualTimeseriesResponse]

func _QuartzAPI_GetActualCrossSection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActualCrossSectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuartzAPIServer).GetActualCrossSection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuartzAPI_GetActualCrossSection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuartzAPIServer).GetActualCrossSection(ctx, req.(*GetActualCrossSectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuartzAPI_GetPredictedCrossSection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPredictedCrossSectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuartzAPIServer).GetPredictedCrossSection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuartzAPI_GetPredictedCrossSection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuartzAPIServer).GetPredictedCrossSection(ctx, req.(*GetPredictedCrossSectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuartzAPI_CreateSolarSite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSiteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuartzAPIServer).CreateSolarSite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuartzAPI_CreateSolarSite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuartzAPIServer).CreateSolarSite(ctx, req.(*CreateSiteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuartzAPI_CreateWindSite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSiteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuartzAPIServer).CreateWindSite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuartzAPI_CreateWindSite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuartzAPIServer).CreateWindSite(ctx, req.(*CreateSiteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuartzAPI_CreateSolarGsp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGspRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuartzAPIServer).CreateSolarGsp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuartzAPI_CreateSolarGsp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuartzAPIServer).CreateSolarGsp(ctx, req.(*CreateGspRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuartzAPI_CreateWindGsp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGspRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuartzAPIServer).CreateWindGsp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuartzAPI_CreateWindGsp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuartzAPIServer).CreateWindGsp(ctx, req.(*CreateGspRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QuartzAPI_ServiceDesc is the grpc.ServiceDesc for QuartzAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QuartzAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.QuartzAPI",
	HandlerType: (*QuartzAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetActualCrossSection",
			Handler:    _QuartzAPI_GetActualCrossSection_Handler,
		},
		{
			MethodName: "GetPredictedCrossSection",
			Handler:    _QuartzAPI_GetPredictedCrossSection_Handler,
		},
		{
			MethodName: "CreateSolarSite",
			Handler:    _QuartzAPI_CreateSolarSite_Handler,
		},
		{
			MethodName: "CreateWindSite",
			Handler:    _QuartzAPI_CreateWindSite_Handler,
		},
		{
			MethodName: "CreateSolarGsp",
			Handler:    _QuartzAPI_CreateSolarGsp_Handler,
		},
		{
			MethodName: "CreateWindGsp",
			Handler:    _QuartzAPI_CreateWindGsp_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetPredictedTimeseries",
			Handler:       _QuartzAPI_GetPredictedTimeseries_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetActualTimeseries",
			Handler:       _QuartzAPI_GetActualTimeseries_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api.proto",
}
