# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: api.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import AsyncGenerator, List

import betterproto
import grpclib


@dataclass
class GetPredictedTimeseriesRequest(betterproto.Message):
    """
    --- GetPredictedTimeseries
    --------------------------------------------------------
    """

    location_ids: List[str] = betterproto.string_field(1)


@dataclass
class GetPredictedTimeseriesResponse(betterproto.Message):
    location_id: str = betterproto.string_field(1)
    yields: List["PredictedYield"] = betterproto.message_field(2)


@dataclass
class PredictedYield(betterproto.Message):
    yield_kw: int = betterproto.int32_field(1)
    timestamp_unix: int = betterproto.int64_field(2)
    uncertainty: "PredictedYieldUncertainty" = betterproto.message_field(3)


@dataclass
class PredictedYieldUncertainty(betterproto.Message):
    lower_kw: int = betterproto.int32_field(1)
    upper_kw: int = betterproto.int32_field(2)


@dataclass
class GetActualTimeseriesRequest(betterproto.Message):
    """
    --- GetActualTimeseries
    -----------------------------------------------------------
    """

    location_ids: List[str] = betterproto.string_field(1)


@dataclass
class GetActualTimeseriesResponse(betterproto.Message):
    location_id: str = betterproto.string_field(1)
    yields: List["ActualYield"] = betterproto.message_field(2)


@dataclass
class ActualYield(betterproto.Message):
    yield_kw: int = betterproto.int32_field(1)
    timestamp_unix: int = betterproto.int64_field(2)


@dataclass
class GetPredictedCrossSectionRequest(betterproto.Message):
    """
    --- GetPredictedCrossSection
    ------------------------------------------------------
    """

    location_ids: List[str] = betterproto.string_field(1)
    timestamp_unix: int = betterproto.int64_field(2)


@dataclass
class GetPredictedCrossSectionResponse(betterproto.Message):
    timestamp_unix: int = betterproto.int64_field(1)
    yields: List["PredictedYieldAtLocation"] = betterproto.message_field(2)


@dataclass
class PredictedYieldAtLocation(betterproto.Message):
    location_id: str = betterproto.string_field(1)
    yield_kw: int = betterproto.int32_field(2)
    uncertainty: "PredictedYieldUncertainty" = betterproto.message_field(3)


@dataclass
class GetActualCrossSectionRequest(betterproto.Message):
    """
    --- GetActualCrossSection
    ---------------------------------------------------------
    """

    location_ids: List[str] = betterproto.string_field(1)
    timestamp_unix: int = betterproto.int64_field(2)


@dataclass
class GetActualCrossSectionResponse(betterproto.Message):
    timestamp_unix: int = betterproto.int64_field(1)
    yields: List["ActualYieldAtLocation"] = betterproto.message_field(2)


@dataclass
class ActualYieldAtLocation(betterproto.Message):
    location_id: str = betterproto.string_field(1)
    yield_kw: int = betterproto.int32_field(2)


@dataclass
class CreateSiteRequest(betterproto.Message):
    """
    --- Locations
    ----------------------------------------------------------------
    """

    name: str = betterproto.string_field(1)
    latitude: float = betterproto.float_field(2)
    longitude: float = betterproto.float_field(3)
    capacity_kw: int = betterproto.int64_field(4)
    metadata: str = betterproto.string_field(5)


@dataclass
class CreateGspRequest(betterproto.Message):
    name: str = betterproto.string_field(1)
    geometry: str = betterproto.string_field(2)
    capacity_kw: int = betterproto.int64_field(3)
    metadata: str = betterproto.string_field(4)


@dataclass
class CreateLocationResponse(betterproto.Message):
    location_id: int = betterproto.int64_field(1)


class QuartzAPIStub(betterproto.ServiceStub):
    async def get_predicted_timeseries(
        self, *, location_ids: List[str] = []
    ) -> AsyncGenerator[GetPredictedTimeseriesResponse, None]:
        """
        GetPredictedTimeseriesRequest is a request for a set of predicted
        yields for one or more locations. The response is a stream of
        GetPredictedTimeseriesResponse messages. each containing the predicted
        yields for a single location.
        """

        request = GetPredictedTimeseriesRequest()
        request.location_ids = location_ids

        async for response in self._unary_stream(
            "/api.QuartzAPI/GetPredictedTimeseries",
            request,
            GetPredictedTimeseriesResponse,
        ):
            yield response

    async def get_actual_timeseries(
        self, *, location_ids: List[str] = []
    ) -> AsyncGenerator[GetActualTimeseriesResponse, None]:
        """
        GetActualTimeseriesRequest is a request for a set of actual yields for
        one or more locations. The response is a stream of
        GetActualTimeseriesResponse messages. each containing the actual yields
        for a single location.
        """

        request = GetActualTimeseriesRequest()
        request.location_ids = location_ids

        async for response in self._unary_stream(
            "/api.QuartzAPI/GetActualTimeseries",
            request,
            GetActualTimeseriesResponse,
        ):
            yield response

    async def get_actual_cross_section(
        self, *, location_ids: List[str] = [], timestamp_unix: int = 0
    ) -> GetActualCrossSectionResponse:
        """
        GetActualCrossSectionRequest is a request for a specific actual yield
        for one or more locations at a single timestamp. The response is a
        GetActualCrossSectionResponse message containing the actual yields for
        each location.
        """

        request = GetActualCrossSectionRequest()
        request.location_ids = location_ids
        request.timestamp_unix = timestamp_unix

        return await self._unary_unary(
            "/api.QuartzAPI/GetActualCrossSection",
            request,
            GetActualCrossSectionResponse,
        )

    async def get_predicted_cross_section(
        self, *, location_ids: List[str] = [], timestamp_unix: int = 0
    ) -> GetPredictedCrossSectionResponse:
        """
        GetPredictedCrossSectionRequest is a request for a specific predicted
        yield for one or more locations at a single timestamp. The response is
        a GetPredictedCrossSectionResponse message containing the predicted
        yields for each location.
        """

        request = GetPredictedCrossSectionRequest()
        request.location_ids = location_ids
        request.timestamp_unix = timestamp_unix

        return await self._unary_unary(
            "/api.QuartzAPI/GetPredictedCrossSection",
            request,
            GetPredictedCrossSectionResponse,
        )

    async def create_solar_site(
        self,
        *,
        name: str = "",
        latitude: float = 0,
        longitude: float = 0,
        capacity_kw: int = 0,
        metadata: str = "",
    ) -> CreateLocationResponse:
        request = CreateSiteRequest()
        request.name = name
        request.latitude = latitude
        request.longitude = longitude
        request.capacity_kw = capacity_kw
        request.metadata = metadata

        return await self._unary_unary(
            "/api.QuartzAPI/CreateSolarSite",
            request,
            CreateLocationResponse,
        )

    async def create_wind_site(
        self,
        *,
        name: str = "",
        latitude: float = 0,
        longitude: float = 0,
        capacity_kw: int = 0,
        metadata: str = "",
    ) -> CreateLocationResponse:
        request = CreateSiteRequest()
        request.name = name
        request.latitude = latitude
        request.longitude = longitude
        request.capacity_kw = capacity_kw
        request.metadata = metadata

        return await self._unary_unary(
            "/api.QuartzAPI/CreateWindSite",
            request,
            CreateLocationResponse,
        )

    async def create_solar_gsp(
        self,
        *,
        name: str = "",
        geometry: str = "",
        capacity_kw: int = 0,
        metadata: str = "",
    ) -> CreateLocationResponse:
        request = CreateGspRequest()
        request.name = name
        request.geometry = geometry
        request.capacity_kw = capacity_kw
        request.metadata = metadata

        return await self._unary_unary(
            "/api.QuartzAPI/CreateSolarGsp",
            request,
            CreateLocationResponse,
        )

    async def create_wind_gsp(
        self,
        *,
        name: str = "",
        geometry: str = "",
        capacity_kw: int = 0,
        metadata: str = "",
    ) -> CreateLocationResponse:
        request = CreateGspRequest()
        request.name = name
        request.geometry = geometry
        request.capacity_kw = capacity_kw
        request.metadata = metadata

        return await self._unary_unary(
            "/api.QuartzAPI/CreateWindGsp",
            request,
            CreateLocationResponse,
        )
