// @generated by protobuf-ts 2.9.6 with parameter output_javascript
// @generated from protobuf file "api.proto" (package "api", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import type { GetLocationResponse } from "./api";
import type { GetLocationRequest } from "./api";
import type { CreateGspRequest } from "./api";
import type { CreateLocationResponse } from "./api";
import type { CreateSiteRequest } from "./api";
import type { GetPredictedCrossSectionResponse } from "./api";
import type { GetPredictedCrossSectionRequest } from "./api";
import type { GetActualCrossSectionResponse } from "./api";
import type { GetActualCrossSectionRequest } from "./api";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { GetActualTimeseriesResponse } from "./api";
import type { GetActualTimeseriesRequest } from "./api";
import type { GetPredictedTimeseriesResponse } from "./api";
import type { GetPredictedTimeseriesRequest } from "./api";
import type { ServerStreamingCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service api.QuartzAPI
 */
export interface IQuartzAPIClient {
    /**
     * @generated from protobuf rpc: GetPredictedTimeseries(api.GetPredictedTimeseriesRequest) returns (stream api.GetPredictedTimeseriesResponse);
     */
    getPredictedTimeseries(input: GetPredictedTimeseriesRequest, options?: RpcOptions): ServerStreamingCall<GetPredictedTimeseriesRequest, GetPredictedTimeseriesResponse>;
    /**
     * @generated from protobuf rpc: GetActualTimeseries(api.GetActualTimeseriesRequest) returns (stream api.GetActualTimeseriesResponse);
     */
    getActualTimeseries(input: GetActualTimeseriesRequest, options?: RpcOptions): ServerStreamingCall<GetActualTimeseriesRequest, GetActualTimeseriesResponse>;
    /**
     * @generated from protobuf rpc: GetActualCrossSection(api.GetActualCrossSectionRequest) returns (api.GetActualCrossSectionResponse);
     */
    getActualCrossSection(input: GetActualCrossSectionRequest, options?: RpcOptions): UnaryCall<GetActualCrossSectionRequest, GetActualCrossSectionResponse>;
    /**
     * @generated from protobuf rpc: GetPredictedCrossSection(api.GetPredictedCrossSectionRequest) returns (api.GetPredictedCrossSectionResponse);
     */
    getPredictedCrossSection(input: GetPredictedCrossSectionRequest, options?: RpcOptions): UnaryCall<GetPredictedCrossSectionRequest, GetPredictedCrossSectionResponse>;
    /**
     * @generated from protobuf rpc: CreateSolarSite(api.CreateSiteRequest) returns (api.CreateLocationResponse);
     */
    createSolarSite(input: CreateSiteRequest, options?: RpcOptions): UnaryCall<CreateSiteRequest, CreateLocationResponse>;
    /**
     * @generated from protobuf rpc: CreateWindSite(api.CreateSiteRequest) returns (api.CreateLocationResponse);
     */
    createWindSite(input: CreateSiteRequest, options?: RpcOptions): UnaryCall<CreateSiteRequest, CreateLocationResponse>;
    /**
     * @generated from protobuf rpc: CreateSolarGsp(api.CreateGspRequest) returns (api.CreateLocationResponse);
     */
    createSolarGsp(input: CreateGspRequest, options?: RpcOptions): UnaryCall<CreateGspRequest, CreateLocationResponse>;
    /**
     * @generated from protobuf rpc: CreateWindGsp(api.CreateGspRequest) returns (api.CreateLocationResponse);
     */
    createWindGsp(input: CreateGspRequest, options?: RpcOptions): UnaryCall<CreateGspRequest, CreateLocationResponse>;
    /**
     * @generated from protobuf rpc: GetSolarSite(api.GetLocationRequest) returns (api.GetLocationResponse);
     */
    getSolarSite(input: GetLocationRequest, options?: RpcOptions): UnaryCall<GetLocationRequest, GetLocationResponse>;
    /**
     * @generated from protobuf rpc: GetSolarGsp(api.GetLocationRequest) returns (api.GetLocationResponse);
     */
    getSolarGsp(input: GetLocationRequest, options?: RpcOptions): UnaryCall<GetLocationRequest, GetLocationResponse>;
}
/**
 * @generated from protobuf service api.QuartzAPI
 */
export declare class QuartzAPIClient implements IQuartzAPIClient, ServiceInfo {
    private readonly _transport;
    typeName: any;
    methods: any;
    options: any;
    constructor(_transport: RpcTransport);
    /**
     * @generated from protobuf rpc: GetPredictedTimeseries(api.GetPredictedTimeseriesRequest) returns (stream api.GetPredictedTimeseriesResponse);
     */
    getPredictedTimeseries(input: GetPredictedTimeseriesRequest, options?: RpcOptions): ServerStreamingCall<GetPredictedTimeseriesRequest, GetPredictedTimeseriesResponse>;
    /**
     * @generated from protobuf rpc: GetActualTimeseries(api.GetActualTimeseriesRequest) returns (stream api.GetActualTimeseriesResponse);
     */
    getActualTimeseries(input: GetActualTimeseriesRequest, options?: RpcOptions): ServerStreamingCall<GetActualTimeseriesRequest, GetActualTimeseriesResponse>;
    /**
     * @generated from protobuf rpc: GetActualCrossSection(api.GetActualCrossSectionRequest) returns (api.GetActualCrossSectionResponse);
     */
    getActualCrossSection(input: GetActualCrossSectionRequest, options?: RpcOptions): UnaryCall<GetActualCrossSectionRequest, GetActualCrossSectionResponse>;
    /**
     * @generated from protobuf rpc: GetPredictedCrossSection(api.GetPredictedCrossSectionRequest) returns (api.GetPredictedCrossSectionResponse);
     */
    getPredictedCrossSection(input: GetPredictedCrossSectionRequest, options?: RpcOptions): UnaryCall<GetPredictedCrossSectionRequest, GetPredictedCrossSectionResponse>;
    /**
     * @generated from protobuf rpc: CreateSolarSite(api.CreateSiteRequest) returns (api.CreateLocationResponse);
     */
    createSolarSite(input: CreateSiteRequest, options?: RpcOptions): UnaryCall<CreateSiteRequest, CreateLocationResponse>;
    /**
     * @generated from protobuf rpc: CreateWindSite(api.CreateSiteRequest) returns (api.CreateLocationResponse);
     */
    createWindSite(input: CreateSiteRequest, options?: RpcOptions): UnaryCall<CreateSiteRequest, CreateLocationResponse>;
    /**
     * @generated from protobuf rpc: CreateSolarGsp(api.CreateGspRequest) returns (api.CreateLocationResponse);
     */
    createSolarGsp(input: CreateGspRequest, options?: RpcOptions): UnaryCall<CreateGspRequest, CreateLocationResponse>;
    /**
     * @generated from protobuf rpc: CreateWindGsp(api.CreateGspRequest) returns (api.CreateLocationResponse);
     */
    createWindGsp(input: CreateGspRequest, options?: RpcOptions): UnaryCall<CreateGspRequest, CreateLocationResponse>;
    /**
     * @generated from protobuf rpc: GetSolarSite(api.GetLocationRequest) returns (api.GetLocationResponse);
     */
    getSolarSite(input: GetLocationRequest, options?: RpcOptions): UnaryCall<GetLocationRequest, GetLocationResponse>;
    /**
     * @generated from protobuf rpc: GetSolarGsp(api.GetLocationRequest) returns (api.GetLocationResponse);
     */
    getSolarGsp(input: GetLocationRequest, options?: RpcOptions): UnaryCall<GetLocationRequest, GetLocationResponse>;
}
