// @generated by protobuf-ts 2.9.6 with parameter output_javascript
// @generated from protobuf file "api.proto" (package "api", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * --- GetPredictedTimeseries --------------------------------------------------------
 *
 * @generated from protobuf message api.GetPredictedTimeseriesRequest
 */
export interface GetPredictedTimeseriesRequest {
    /**
     * @generated from protobuf field: repeated string location_ids = 1;
     */
    locationIds: string[];
}
/**
 * @generated from protobuf message api.GetPredictedTimeseriesResponse
 */
export interface GetPredictedTimeseriesResponse {
    /**
     * @generated from protobuf field: string location_id = 1;
     */
    locationId: string;
    /**
     * @generated from protobuf field: repeated api.PredictedYield yields = 2;
     */
    yields: PredictedYield[];
}
/**
 * @generated from protobuf message api.PredictedYield
 */
export interface PredictedYield {
    /**
     * @generated from protobuf field: int32 yield_kw = 1;
     */
    yieldKw: number;
    /**
     * @generated from protobuf field: int64 timestamp_unix = 2;
     */
    timestampUnix: bigint;
    /**
     * @generated from protobuf field: api.PredictedYieldUncertainty uncertainty = 3;
     */
    uncertainty?: PredictedYieldUncertainty;
}
/**
 * @generated from protobuf message api.PredictedYieldUncertainty
 */
export interface PredictedYieldUncertainty {
    /**
     * @generated from protobuf field: int32 lower_kw = 1;
     */
    lowerKw: number;
    /**
     * @generated from protobuf field: int32 upper_kw = 2;
     */
    upperKw: number;
}
/**
 * --- GetActualTimeseries -----------------------------------------------------------
 *
 * @generated from protobuf message api.GetActualTimeseriesRequest
 */
export interface GetActualTimeseriesRequest {
    /**
     * @generated from protobuf field: repeated string location_ids = 1;
     */
    locationIds: string[];
}
/**
 * @generated from protobuf message api.GetActualTimeseriesResponse
 */
export interface GetActualTimeseriesResponse {
    /**
     * @generated from protobuf field: string location_id = 1;
     */
    locationId: string;
    /**
     * @generated from protobuf field: repeated api.ActualYield yields = 2;
     */
    yields: ActualYield[];
}
/**
 * @generated from protobuf message api.ActualYield
 */
export interface ActualYield {
    /**
     * @generated from protobuf field: int32 yield_kw = 1;
     */
    yieldKw: number;
    /**
     * @generated from protobuf field: int64 timestamp_unix = 2;
     */
    timestampUnix: bigint;
}
/**
 * --- GetPredictedCrossSection ------------------------------------------------------
 *
 * @generated from protobuf message api.GetPredictedCrossSectionRequest
 */
export interface GetPredictedCrossSectionRequest {
    /**
     * @generated from protobuf field: repeated string location_ids = 1;
     */
    locationIds: string[];
    /**
     * @generated from protobuf field: int64 timestamp_unix = 2;
     */
    timestampUnix: bigint;
}
/**
 * @generated from protobuf message api.GetPredictedCrossSectionResponse
 */
export interface GetPredictedCrossSectionResponse {
    /**
     * @generated from protobuf field: int64 timestamp_unix = 1;
     */
    timestampUnix: bigint;
    /**
     * @generated from protobuf field: repeated api.PredictedYieldAtLocation yields = 2;
     */
    yields: PredictedYieldAtLocation[];
}
/**
 * @generated from protobuf message api.PredictedYieldAtLocation
 */
export interface PredictedYieldAtLocation {
    /**
     * @generated from protobuf field: string location_id = 1;
     */
    locationId: string;
    /**
     * @generated from protobuf field: int32 yield_kw = 2;
     */
    yieldKw: number;
    /**
     * @generated from protobuf field: api.PredictedYieldUncertainty uncertainty = 3;
     */
    uncertainty?: PredictedYieldUncertainty;
}
/**
 * --- GetActualCrossSection ---------------------------------------------------------
 *
 * @generated from protobuf message api.GetActualCrossSectionRequest
 */
export interface GetActualCrossSectionRequest {
    /**
     * @generated from protobuf field: repeated string location_ids = 1;
     */
    locationIds: string[];
    /**
     * @generated from protobuf field: int64 timestamp_unix = 2;
     */
    timestampUnix: bigint;
}
/**
 * @generated from protobuf message api.GetActualCrossSectionResponse
 */
export interface GetActualCrossSectionResponse {
    /**
     * @generated from protobuf field: int64 timestamp_unix = 1;
     */
    timestampUnix: bigint;
    /**
     * @generated from protobuf field: repeated api.ActualYieldAtLocation yields = 2;
     */
    yields: ActualYieldAtLocation[];
}
/**
 * @generated from protobuf message api.ActualYieldAtLocation
 */
export interface ActualYieldAtLocation {
    /**
     * @generated from protobuf field: string location_id = 1;
     */
    locationId: string;
    /**
     * @generated from protobuf field: int32 yield_kw = 2;
     */
    yieldKw: number;
}
/**
 * --- Locations ----------------------------------------------------------------
 *
 * @generated from protobuf message api.CreateSiteRequest
 */
export interface CreateSiteRequest {
    /**
     * @generated from protobuf field: string name = 1;
     */
    name: string;
    /**
     * @generated from protobuf field: float latitude = 2;
     */
    latitude: number;
    /**
     * @generated from protobuf field: float longitude = 3;
     */
    longitude: number;
    /**
     * @generated from protobuf field: int64 capacity_kw = 4;
     */
    capacityKw: bigint;
    /**
     * @generated from protobuf field: string metadata = 5;
     */
    metadata: string;
}
/**
 * @generated from protobuf message api.CreateGspRequest
 */
export interface CreateGspRequest {
    /**
     * @generated from protobuf field: string name = 1;
     */
    name: string;
    /**
     * @generated from protobuf field: string geometry = 2;
     */
    geometry: string;
    /**
     * @generated from protobuf field: int64 capacity_kw = 3;
     */
    capacityKw: bigint;
    /**
     * @generated from protobuf field: string metadata = 4;
     */
    metadata: string;
}
/**
 * @generated from protobuf message api.CreateLocationResponse
 */
export interface CreateLocationResponse {
    /**
     * @generated from protobuf field: int64 location_id = 1;
     */
    locationId: bigint;
}
declare class GetPredictedTimeseriesRequest$Type extends MessageType<GetPredictedTimeseriesRequest> {
    constructor();
    create(value?: PartialMessage<GetPredictedTimeseriesRequest>): GetPredictedTimeseriesRequest;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetPredictedTimeseriesRequest): GetPredictedTimeseriesRequest;
    internalBinaryWrite(message: GetPredictedTimeseriesRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message api.GetPredictedTimeseriesRequest
 */
export declare const GetPredictedTimeseriesRequest: GetPredictedTimeseriesRequest$Type;
declare class GetPredictedTimeseriesResponse$Type extends MessageType<GetPredictedTimeseriesResponse> {
    constructor();
    create(value?: PartialMessage<GetPredictedTimeseriesResponse>): GetPredictedTimeseriesResponse;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetPredictedTimeseriesResponse): GetPredictedTimeseriesResponse;
    internalBinaryWrite(message: GetPredictedTimeseriesResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message api.GetPredictedTimeseriesResponse
 */
export declare const GetPredictedTimeseriesResponse: GetPredictedTimeseriesResponse$Type;
declare class PredictedYield$Type extends MessageType<PredictedYield> {
    constructor();
    create(value?: PartialMessage<PredictedYield>): PredictedYield;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PredictedYield): PredictedYield;
    internalBinaryWrite(message: PredictedYield, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message api.PredictedYield
 */
export declare const PredictedYield: PredictedYield$Type;
declare class PredictedYieldUncertainty$Type extends MessageType<PredictedYieldUncertainty> {
    constructor();
    create(value?: PartialMessage<PredictedYieldUncertainty>): PredictedYieldUncertainty;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PredictedYieldUncertainty): PredictedYieldUncertainty;
    internalBinaryWrite(message: PredictedYieldUncertainty, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message api.PredictedYieldUncertainty
 */
export declare const PredictedYieldUncertainty: PredictedYieldUncertainty$Type;
declare class GetActualTimeseriesRequest$Type extends MessageType<GetActualTimeseriesRequest> {
    constructor();
    create(value?: PartialMessage<GetActualTimeseriesRequest>): GetActualTimeseriesRequest;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetActualTimeseriesRequest): GetActualTimeseriesRequest;
    internalBinaryWrite(message: GetActualTimeseriesRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message api.GetActualTimeseriesRequest
 */
export declare const GetActualTimeseriesRequest: GetActualTimeseriesRequest$Type;
declare class GetActualTimeseriesResponse$Type extends MessageType<GetActualTimeseriesResponse> {
    constructor();
    create(value?: PartialMessage<GetActualTimeseriesResponse>): GetActualTimeseriesResponse;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetActualTimeseriesResponse): GetActualTimeseriesResponse;
    internalBinaryWrite(message: GetActualTimeseriesResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message api.GetActualTimeseriesResponse
 */
export declare const GetActualTimeseriesResponse: GetActualTimeseriesResponse$Type;
declare class ActualYield$Type extends MessageType<ActualYield> {
    constructor();
    create(value?: PartialMessage<ActualYield>): ActualYield;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ActualYield): ActualYield;
    internalBinaryWrite(message: ActualYield, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message api.ActualYield
 */
export declare const ActualYield: ActualYield$Type;
declare class GetPredictedCrossSectionRequest$Type extends MessageType<GetPredictedCrossSectionRequest> {
    constructor();
    create(value?: PartialMessage<GetPredictedCrossSectionRequest>): GetPredictedCrossSectionRequest;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetPredictedCrossSectionRequest): GetPredictedCrossSectionRequest;
    internalBinaryWrite(message: GetPredictedCrossSectionRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message api.GetPredictedCrossSectionRequest
 */
export declare const GetPredictedCrossSectionRequest: GetPredictedCrossSectionRequest$Type;
declare class GetPredictedCrossSectionResponse$Type extends MessageType<GetPredictedCrossSectionResponse> {
    constructor();
    create(value?: PartialMessage<GetPredictedCrossSectionResponse>): GetPredictedCrossSectionResponse;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetPredictedCrossSectionResponse): GetPredictedCrossSectionResponse;
    internalBinaryWrite(message: GetPredictedCrossSectionResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message api.GetPredictedCrossSectionResponse
 */
export declare const GetPredictedCrossSectionResponse: GetPredictedCrossSectionResponse$Type;
declare class PredictedYieldAtLocation$Type extends MessageType<PredictedYieldAtLocation> {
    constructor();
    create(value?: PartialMessage<PredictedYieldAtLocation>): PredictedYieldAtLocation;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PredictedYieldAtLocation): PredictedYieldAtLocation;
    internalBinaryWrite(message: PredictedYieldAtLocation, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message api.PredictedYieldAtLocation
 */
export declare const PredictedYieldAtLocation: PredictedYieldAtLocation$Type;
declare class GetActualCrossSectionRequest$Type extends MessageType<GetActualCrossSectionRequest> {
    constructor();
    create(value?: PartialMessage<GetActualCrossSectionRequest>): GetActualCrossSectionRequest;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetActualCrossSectionRequest): GetActualCrossSectionRequest;
    internalBinaryWrite(message: GetActualCrossSectionRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message api.GetActualCrossSectionRequest
 */
export declare const GetActualCrossSectionRequest: GetActualCrossSectionRequest$Type;
declare class GetActualCrossSectionResponse$Type extends MessageType<GetActualCrossSectionResponse> {
    constructor();
    create(value?: PartialMessage<GetActualCrossSectionResponse>): GetActualCrossSectionResponse;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetActualCrossSectionResponse): GetActualCrossSectionResponse;
    internalBinaryWrite(message: GetActualCrossSectionResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message api.GetActualCrossSectionResponse
 */
export declare const GetActualCrossSectionResponse: GetActualCrossSectionResponse$Type;
declare class ActualYieldAtLocation$Type extends MessageType<ActualYieldAtLocation> {
    constructor();
    create(value?: PartialMessage<ActualYieldAtLocation>): ActualYieldAtLocation;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ActualYieldAtLocation): ActualYieldAtLocation;
    internalBinaryWrite(message: ActualYieldAtLocation, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message api.ActualYieldAtLocation
 */
export declare const ActualYieldAtLocation: ActualYieldAtLocation$Type;
declare class CreateSiteRequest$Type extends MessageType<CreateSiteRequest> {
    constructor();
    create(value?: PartialMessage<CreateSiteRequest>): CreateSiteRequest;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateSiteRequest): CreateSiteRequest;
    internalBinaryWrite(message: CreateSiteRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message api.CreateSiteRequest
 */
export declare const CreateSiteRequest: CreateSiteRequest$Type;
declare class CreateGspRequest$Type extends MessageType<CreateGspRequest> {
    constructor();
    create(value?: PartialMessage<CreateGspRequest>): CreateGspRequest;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateGspRequest): CreateGspRequest;
    internalBinaryWrite(message: CreateGspRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message api.CreateGspRequest
 */
export declare const CreateGspRequest: CreateGspRequest$Type;
declare class CreateLocationResponse$Type extends MessageType<CreateLocationResponse> {
    constructor();
    create(value?: PartialMessage<CreateLocationResponse>): CreateLocationResponse;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateLocationResponse): CreateLocationResponse;
    internalBinaryWrite(message: CreateLocationResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message api.CreateLocationResponse
 */
export declare const CreateLocationResponse: CreateLocationResponse$Type;
/**
 * @generated ServiceType for protobuf service api.QuartzAPI
 */
export declare const QuartzAPI: any;
export {};
