// @generated by protobuf-ts 2.9.6 with parameter output_javascript
// @generated from protobuf file "api.proto" (package "api", syntax proto3)
// tslint:disable
// @generated by protobuf-ts 2.9.6 with parameter output_javascript
// @generated from protobuf file "api.proto" (package "api", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import { WireType } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
// @generated message type with reflection information, may provide speed optimized methods
class GetPredictedTimeseriesRequest$Type extends MessageType {
    constructor() {
        super("api.GetPredictedTimeseriesRequest", [
            { no: 1, name: "location_ids", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        message.locationIds = [];
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated string location_ids */ 1:
                    message.locationIds.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        /* repeated string location_ids = 1; */
        for (let i = 0; i < message.locationIds.length; i++)
            writer.tag(1, WireType.LengthDelimited).string(message.locationIds[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message api.GetPredictedTimeseriesRequest
 */
export const GetPredictedTimeseriesRequest = new GetPredictedTimeseriesRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetPredictedTimeseriesResponse$Type extends MessageType {
    constructor() {
        super("api.GetPredictedTimeseriesResponse", [
            { no: 1, name: "location_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "yields", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => PredictedYield }
        ]);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        message.locationId = "";
        message.yields = [];
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string location_id */ 1:
                    message.locationId = reader.string();
                    break;
                case /* repeated api.PredictedYield yields */ 2:
                    message.yields.push(PredictedYield.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        /* string location_id = 1; */
        if (message.locationId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.locationId);
        /* repeated api.PredictedYield yields = 2; */
        for (let i = 0; i < message.yields.length; i++)
            PredictedYield.internalBinaryWrite(message.yields[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message api.GetPredictedTimeseriesResponse
 */
export const GetPredictedTimeseriesResponse = new GetPredictedTimeseriesResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PredictedYield$Type extends MessageType {
    constructor() {
        super("api.PredictedYield", [
            { no: 1, name: "yield_kw", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "timestamp_unix", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 3, name: "uncertainty", kind: "message", T: () => PredictedYieldUncertainty }
        ]);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        message.yieldKw = 0;
        message.timestampUnix = 0n;
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 yield_kw */ 1:
                    message.yieldKw = reader.int32();
                    break;
                case /* int64 timestamp_unix */ 2:
                    message.timestampUnix = reader.int64().toBigInt();
                    break;
                case /* api.PredictedYieldUncertainty uncertainty */ 3:
                    message.uncertainty = PredictedYieldUncertainty.internalBinaryRead(reader, reader.uint32(), options, message.uncertainty);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        /* int32 yield_kw = 1; */
        if (message.yieldKw !== 0)
            writer.tag(1, WireType.Varint).int32(message.yieldKw);
        /* int64 timestamp_unix = 2; */
        if (message.timestampUnix !== 0n)
            writer.tag(2, WireType.Varint).int64(message.timestampUnix);
        /* api.PredictedYieldUncertainty uncertainty = 3; */
        if (message.uncertainty)
            PredictedYieldUncertainty.internalBinaryWrite(message.uncertainty, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message api.PredictedYield
 */
export const PredictedYield = new PredictedYield$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PredictedYieldUncertainty$Type extends MessageType {
    constructor() {
        super("api.PredictedYieldUncertainty", [
            { no: 1, name: "lower_kw", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "upper_kw", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        message.lowerKw = 0;
        message.upperKw = 0;
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 lower_kw */ 1:
                    message.lowerKw = reader.int32();
                    break;
                case /* int32 upper_kw */ 2:
                    message.upperKw = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        /* int32 lower_kw = 1; */
        if (message.lowerKw !== 0)
            writer.tag(1, WireType.Varint).int32(message.lowerKw);
        /* int32 upper_kw = 2; */
        if (message.upperKw !== 0)
            writer.tag(2, WireType.Varint).int32(message.upperKw);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message api.PredictedYieldUncertainty
 */
export const PredictedYieldUncertainty = new PredictedYieldUncertainty$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetActualTimeseriesRequest$Type extends MessageType {
    constructor() {
        super("api.GetActualTimeseriesRequest", [
            { no: 1, name: "location_ids", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        message.locationIds = [];
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated string location_ids */ 1:
                    message.locationIds.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        /* repeated string location_ids = 1; */
        for (let i = 0; i < message.locationIds.length; i++)
            writer.tag(1, WireType.LengthDelimited).string(message.locationIds[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message api.GetActualTimeseriesRequest
 */
export const GetActualTimeseriesRequest = new GetActualTimeseriesRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetActualTimeseriesResponse$Type extends MessageType {
    constructor() {
        super("api.GetActualTimeseriesResponse", [
            { no: 1, name: "location_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "yields", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => ActualYield }
        ]);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        message.locationId = "";
        message.yields = [];
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string location_id */ 1:
                    message.locationId = reader.string();
                    break;
                case /* repeated api.ActualYield yields */ 2:
                    message.yields.push(ActualYield.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        /* string location_id = 1; */
        if (message.locationId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.locationId);
        /* repeated api.ActualYield yields = 2; */
        for (let i = 0; i < message.yields.length; i++)
            ActualYield.internalBinaryWrite(message.yields[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message api.GetActualTimeseriesResponse
 */
export const GetActualTimeseriesResponse = new GetActualTimeseriesResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ActualYield$Type extends MessageType {
    constructor() {
        super("api.ActualYield", [
            { no: 1, name: "yield_kw", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "timestamp_unix", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        message.yieldKw = 0;
        message.timestampUnix = 0n;
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 yield_kw */ 1:
                    message.yieldKw = reader.int32();
                    break;
                case /* int64 timestamp_unix */ 2:
                    message.timestampUnix = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        /* int32 yield_kw = 1; */
        if (message.yieldKw !== 0)
            writer.tag(1, WireType.Varint).int32(message.yieldKw);
        /* int64 timestamp_unix = 2; */
        if (message.timestampUnix !== 0n)
            writer.tag(2, WireType.Varint).int64(message.timestampUnix);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message api.ActualYield
 */
export const ActualYield = new ActualYield$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetPredictedCrossSectionRequest$Type extends MessageType {
    constructor() {
        super("api.GetPredictedCrossSectionRequest", [
            { no: 1, name: "location_ids", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "timestamp_unix", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        message.locationIds = [];
        message.timestampUnix = 0n;
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated string location_ids */ 1:
                    message.locationIds.push(reader.string());
                    break;
                case /* int64 timestamp_unix */ 2:
                    message.timestampUnix = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        /* repeated string location_ids = 1; */
        for (let i = 0; i < message.locationIds.length; i++)
            writer.tag(1, WireType.LengthDelimited).string(message.locationIds[i]);
        /* int64 timestamp_unix = 2; */
        if (message.timestampUnix !== 0n)
            writer.tag(2, WireType.Varint).int64(message.timestampUnix);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message api.GetPredictedCrossSectionRequest
 */
export const GetPredictedCrossSectionRequest = new GetPredictedCrossSectionRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetPredictedCrossSectionResponse$Type extends MessageType {
    constructor() {
        super("api.GetPredictedCrossSectionResponse", [
            { no: 1, name: "timestamp_unix", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "yields", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => PredictedYieldAtLocation }
        ]);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        message.timestampUnix = 0n;
        message.yields = [];
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 timestamp_unix */ 1:
                    message.timestampUnix = reader.int64().toBigInt();
                    break;
                case /* repeated api.PredictedYieldAtLocation yields */ 2:
                    message.yields.push(PredictedYieldAtLocation.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        /* int64 timestamp_unix = 1; */
        if (message.timestampUnix !== 0n)
            writer.tag(1, WireType.Varint).int64(message.timestampUnix);
        /* repeated api.PredictedYieldAtLocation yields = 2; */
        for (let i = 0; i < message.yields.length; i++)
            PredictedYieldAtLocation.internalBinaryWrite(message.yields[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message api.GetPredictedCrossSectionResponse
 */
export const GetPredictedCrossSectionResponse = new GetPredictedCrossSectionResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PredictedYieldAtLocation$Type extends MessageType {
    constructor() {
        super("api.PredictedYieldAtLocation", [
            { no: 1, name: "location_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "yield_kw", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "uncertainty", kind: "message", T: () => PredictedYieldUncertainty }
        ]);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        message.locationId = "";
        message.yieldKw = 0;
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string location_id */ 1:
                    message.locationId = reader.string();
                    break;
                case /* int32 yield_kw */ 2:
                    message.yieldKw = reader.int32();
                    break;
                case /* api.PredictedYieldUncertainty uncertainty */ 3:
                    message.uncertainty = PredictedYieldUncertainty.internalBinaryRead(reader, reader.uint32(), options, message.uncertainty);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        /* string location_id = 1; */
        if (message.locationId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.locationId);
        /* int32 yield_kw = 2; */
        if (message.yieldKw !== 0)
            writer.tag(2, WireType.Varint).int32(message.yieldKw);
        /* api.PredictedYieldUncertainty uncertainty = 3; */
        if (message.uncertainty)
            PredictedYieldUncertainty.internalBinaryWrite(message.uncertainty, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message api.PredictedYieldAtLocation
 */
export const PredictedYieldAtLocation = new PredictedYieldAtLocation$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetActualCrossSectionRequest$Type extends MessageType {
    constructor() {
        super("api.GetActualCrossSectionRequest", [
            { no: 1, name: "location_ids", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "timestamp_unix", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        message.locationIds = [];
        message.timestampUnix = 0n;
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated string location_ids */ 1:
                    message.locationIds.push(reader.string());
                    break;
                case /* int64 timestamp_unix */ 2:
                    message.timestampUnix = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        /* repeated string location_ids = 1; */
        for (let i = 0; i < message.locationIds.length; i++)
            writer.tag(1, WireType.LengthDelimited).string(message.locationIds[i]);
        /* int64 timestamp_unix = 2; */
        if (message.timestampUnix !== 0n)
            writer.tag(2, WireType.Varint).int64(message.timestampUnix);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message api.GetActualCrossSectionRequest
 */
export const GetActualCrossSectionRequest = new GetActualCrossSectionRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetActualCrossSectionResponse$Type extends MessageType {
    constructor() {
        super("api.GetActualCrossSectionResponse", [
            { no: 1, name: "timestamp_unix", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "yields", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => ActualYieldAtLocation }
        ]);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        message.timestampUnix = 0n;
        message.yields = [];
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 timestamp_unix */ 1:
                    message.timestampUnix = reader.int64().toBigInt();
                    break;
                case /* repeated api.ActualYieldAtLocation yields */ 2:
                    message.yields.push(ActualYieldAtLocation.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        /* int64 timestamp_unix = 1; */
        if (message.timestampUnix !== 0n)
            writer.tag(1, WireType.Varint).int64(message.timestampUnix);
        /* repeated api.ActualYieldAtLocation yields = 2; */
        for (let i = 0; i < message.yields.length; i++)
            ActualYieldAtLocation.internalBinaryWrite(message.yields[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message api.GetActualCrossSectionResponse
 */
export const GetActualCrossSectionResponse = new GetActualCrossSectionResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ActualYieldAtLocation$Type extends MessageType {
    constructor() {
        super("api.ActualYieldAtLocation", [
            { no: 1, name: "location_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "yield_kw", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        message.locationId = "";
        message.yieldKw = 0;
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string location_id */ 1:
                    message.locationId = reader.string();
                    break;
                case /* int32 yield_kw */ 2:
                    message.yieldKw = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        /* string location_id = 1; */
        if (message.locationId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.locationId);
        /* int32 yield_kw = 2; */
        if (message.yieldKw !== 0)
            writer.tag(2, WireType.Varint).int32(message.yieldKw);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message api.ActualYieldAtLocation
 */
export const ActualYieldAtLocation = new ActualYieldAtLocation$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreateSiteRequest$Type extends MessageType {
    constructor() {
        super("api.CreateSiteRequest", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "latitude", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 3, name: "longitude", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 4, name: "capacity_kw", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 5, name: "metadata", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        message.name = "";
        message.latitude = 0;
        message.longitude = 0;
        message.capacityKw = 0n;
        message.metadata = "";
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string name */ 1:
                    message.name = reader.string();
                    break;
                case /* float latitude */ 2:
                    message.latitude = reader.float();
                    break;
                case /* float longitude */ 3:
                    message.longitude = reader.float();
                    break;
                case /* int64 capacity_kw */ 4:
                    message.capacityKw = reader.int64().toBigInt();
                    break;
                case /* string metadata */ 5:
                    message.metadata = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        /* string name = 1; */
        if (message.name !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.name);
        /* float latitude = 2; */
        if (message.latitude !== 0)
            writer.tag(2, WireType.Bit32).float(message.latitude);
        /* float longitude = 3; */
        if (message.longitude !== 0)
            writer.tag(3, WireType.Bit32).float(message.longitude);
        /* int64 capacity_kw = 4; */
        if (message.capacityKw !== 0n)
            writer.tag(4, WireType.Varint).int64(message.capacityKw);
        /* string metadata = 5; */
        if (message.metadata !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.metadata);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message api.CreateSiteRequest
 */
export const CreateSiteRequest = new CreateSiteRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreateGspRequest$Type extends MessageType {
    constructor() {
        super("api.CreateGspRequest", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "geometry", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "capacity_kw", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 4, name: "metadata", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        message.name = "";
        message.geometry = "";
        message.capacityKw = 0n;
        message.metadata = "";
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string name */ 1:
                    message.name = reader.string();
                    break;
                case /* string geometry */ 2:
                    message.geometry = reader.string();
                    break;
                case /* int64 capacity_kw */ 3:
                    message.capacityKw = reader.int64().toBigInt();
                    break;
                case /* string metadata */ 4:
                    message.metadata = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        /* string name = 1; */
        if (message.name !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.name);
        /* string geometry = 2; */
        if (message.geometry !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.geometry);
        /* int64 capacity_kw = 3; */
        if (message.capacityKw !== 0n)
            writer.tag(3, WireType.Varint).int64(message.capacityKw);
        /* string metadata = 4; */
        if (message.metadata !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.metadata);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message api.CreateGspRequest
 */
export const CreateGspRequest = new CreateGspRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreateLocationResponse$Type extends MessageType {
    constructor() {
        super("api.CreateLocationResponse", [
            { no: 1, name: "location_id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        message.locationId = 0n;
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 location_id */ 1:
                    message.locationId = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        /* int64 location_id = 1; */
        if (message.locationId !== 0n)
            writer.tag(1, WireType.Varint).int64(message.locationId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message api.CreateLocationResponse
 */
export const CreateLocationResponse = new CreateLocationResponse$Type();
/**
 * @generated ServiceType for protobuf service api.QuartzAPI
 */
export const QuartzAPI = new ServiceType("api.QuartzAPI", [
    { name: "GetPredictedTimeseries", serverStreaming: true, options: {}, I: GetPredictedTimeseriesRequest, O: GetPredictedTimeseriesResponse },
    { name: "GetActualTimeseries", serverStreaming: true, options: {}, I: GetActualTimeseriesRequest, O: GetActualTimeseriesResponse },
    { name: "GetActualCrossSection", options: {}, I: GetActualCrossSectionRequest, O: GetActualCrossSectionResponse },
    { name: "GetPredictedCrossSection", options: {}, I: GetPredictedCrossSectionRequest, O: GetPredictedCrossSectionResponse },
    { name: "CreateSolarSite", options: {}, I: CreateSiteRequest, O: CreateLocationResponse },
    { name: "CreateWindSite", options: {}, I: CreateSiteRequest, O: CreateLocationResponse },
    { name: "CreateSolarGsp", options: {}, I: CreateGspRequest, O: CreateLocationResponse },
    { name: "CreateWindGsp", options: {}, I: CreateGspRequest, O: CreateLocationResponse }
]);
