syntax = "proto3";

option go_package = "github.com/devsjc/fcfs/api/src/internal/models";

package api;

service QuartzAPI {
  rpc GetPredictedTimeseries(GetPredictedTimeseriesRequest) returns (stream GetPredictedTimeseriesResponse) {}
  rpc GetActualTimeseries(GetActualTimeseriesRequest) returns (stream GetActualTimeseriesResponse) {}
  rpc GetActualCrossSection(GetActualCrossSectionRequest) returns (GetActualCrossSectionResponse) {}
  rpc GetPredictedCrossSection(GetPredictedCrossSectionRequest) returns (GetPredictedCrossSectionResponse) {}

  rpc CreateSolarSite(CreateSiteRequest) returns (CreateLocationResponse) {}
  rpc CreateWindSite(CreateSiteRequest) returns (CreateLocationResponse) {}
  rpc CreateSolarGsp(CreateGspRequest) returns (CreateLocationResponse) {}
  rpc CreateWindGsp(CreateGspRequest) returns (CreateLocationResponse) {}

  rpc GetSolarSite(GetLocationRequest) returns (GetLocationResponse) {}
  rpc GetSolarGsp(GetLocationRequest) returns (GetLocationResponse) {}

}

// --- GetPredictedTimeseries --------------------------------------------------------
message GetPredictedTimeseriesRequest {
  repeated string location_ids = 1;
}

message GetPredictedTimeseriesResponse {
  string location_id = 1;
  repeated PredictedYield yields = 2;
}

message PredictedYield {
  int32 yield_kw = 1;
  int64 timestamp_unix = 2;
  PredictedYieldUncertainty uncertainty = 3;
}

message PredictedYieldUncertainty {
  int32 lower_kw = 1;
  int32 upper_kw = 2;
}

// --- GetActualTimeseries -----------------------------------------------------------
message GetActualTimeseriesRequest {
  repeated string location_ids = 1;
}

message GetActualTimeseriesResponse {
  string location_id = 1;
  repeated ActualYield yields = 2;
}

message ActualYield {
  int32 yield_kw = 1;
  int64 timestamp_unix = 2;
}

// --- GetPredictedCrossSection ------------------------------------------------------
message GetPredictedCrossSectionRequest {
  repeated string location_ids = 1;
  int64 timestamp_unix = 2;
}

message GetPredictedCrossSectionResponse {
  int64 timestamp_unix = 1;
  repeated PredictedYieldAtLocation yields = 2;
}

message PredictedYieldAtLocation {
  string location_id = 1;
  int32 yield_kw = 2;
  PredictedYieldUncertainty uncertainty = 3;
}

// --- GetActualCrossSection ---------------------------------------------------------
message GetActualCrossSectionRequest {
  repeated string location_ids = 1;
  int64 timestamp_unix = 2;
}

message GetActualCrossSectionResponse {
  int64 timestamp_unix = 1;
  repeated ActualYieldAtLocation yields = 2;
}

message ActualYieldAtLocation {
  string location_id = 1;
  int32 yield_kw = 2;
}

// --- Locations ----------------------------------------------------------------
message CreateSiteRequest {
  string name = 1;
  float latitude = 2;
  float longitude = 3;
  int32 capacity_kw = 4;
  string metadata = 5;
}

message CreateGspRequest {
  string name = 1;
  string geometry = 2;
  int32 capacity_mw = 3;
  string metadata = 4;
}

message CreateLocationResponse {
  int64 location_id = 1;
}

message GetLocationRequest {
  string location_id = 1;
}

message GetLocationResponse {
  string location_id = 1;
  string name = 2;
  float latitude = 3;
  float longitude = 4;
  int32 capacity_kw = 5;
  string metadata = 6;
}

